# Generated by Django 5.1.3 on 2024-11-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
