# Generated by Django 5.1.3 on 2024-11-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='Services/'),
        ),
    ]
